export const site = {
  name: "Jasmine Jackson",
  role: "Product Designer",
  heroBlurb:
    "I'm a product designer who roots my ideas in user needs and grows thoughtful, impactful experiences.",
  about: {
    headshot: "/about/garden/headshot-v4.jpg",
    heading: "Welcome to my garden!",
    paragraphs: [
      "Jasmine Jackson is a San Francisco–based Product Designer specializing in interactive systems, conversational AI, and end-to-end user experiences. With a background spanning enterprise platforms and rapid prototyping, I bridge the gap between complex technical infrastructure and intuitive, human-centered design.",
      "My approach combines systemic rigor with creative exploration. Whether engineering scalable design patterns, building live contextual prototypes with modern AI tools, or experimenting with digital and tactile media, I focus on crafting interfaces that feel seamless, expressive, and purposeful.",
      "When I'm not designing screens, I'm usually building diy home decor, going on hikes practicing yoga, or training for my next half marathon around the Bay Area.",
    ],
    photos: [
      { src: "/about/garden/img-0022.jpg", aspect: 412 / 412 },
      { src: "/about/garden/img-5118.jpg", aspect: 413 / 474 },
      { src: "/about/garden/img-8668.jpg", aspect: 412 / 427 },
      { src: "/about/garden/img-5480.jpg", aspect: 412 / 437 },
      { src: "/about/garden/img-5432.jpg", aspect: 398 / 531 },
      { src: "/about/garden/img-2957.jpg", aspect: 398 / 530 },
      { src: "/about/garden/img-4648.jpg", aspect: 394 / 430 },
      { src: "/about/garden/img-6542.jpg", aspect: 396 / 267 },
      { src: "/about/garden/img-4868.jpg", aspect: 349 / 466 },
      { src: "/about/garden/img-5047.jpg", aspect: 348 / 348 },
      { src: "/about/garden/img-0034.jpg", aspect: 349 / 465 },
      { src: "/about/garden/img-4924.jpg", aspect: 353 / 471 },
    ],
  },
  experience: {
    label: "My experience",
    heading: "My past experience including full-time, leadership, and internships",
    items: [
      { name: "QuickBooks", role: "Product Designer II", icon: "/home/experience/quickbooks.png", rounded: false },
      { name: "Intuit", role: "Associate Product Manager", icon: "/home/experience/intuit.png", rounded: true },
      { name: "Target", role: "Marketing Intern", icon: "/home/experience/target-bullseye.png", rounded: true },
      { name: "Design U", role: "Digital Consultant, VP of Events", icon: "/home/experience/design-u.png", rounded: true },
      { name: "Obvi Design", role: "Design Research Intern", icon: "/home/experience/obvi-design-cropped.gif", rounded: true },
      { name: "Carlson School of Management", role: "Graphic Designer", icon: "/home/experience/carlson.jpg", rounded: true },
    ],
  },
  tools: {
    label: "Tools I use",
    heading: "Click to see what I do with them",
    items: [
      { name: "Figma", icon: "/home/tools/figma.svg", bg: "#f0ebe1", text: "#3d3527", blurb: "My home base for design — wireframes, high-fidelity mockups, and prototyping every case study on this site." },
      { name: "ChatGPT", icon: "/home/tools/chatgpt-logo.png", bg: "#b7d9b1", text: "#1f3a1a", blurb: "My go-to for brainstorming, rubber-ducking ideas, and getting a fast second opinion on writing." },
      { name: "Claude Code", icon: "/home/tools/claude-logo.png", bg: "#b9d4e0", text: "#1c2f38", blurb: "I used Claude Code to build this entire portfolio — layout, copy, and every case study rebuild." },
      { name: "Framer", icon: "/home/tools/framer.svg", bg: "#9fc9a8", text: "#16301f", blurb: "For quick, high-fidelity motion prototypes when a static Figma frame isn't enough to sell an interaction." },
      { name: "Cursor", icon: "/home/tools/cursor-logo.png", bg: "#cfe3f7", text: "#1a2b3d", blurb: "My AI-native code editor for vibe-coding quick prototypes and testing ideas outside of Figma." },
      { name: "GitHub", icon: "/home/tools/github.svg", bg: "#ddd0b8", text: "#362c1a", blurb: "Where I version and host the code behind my personal projects, like this site and Homing." },
      { name: "Adobe", icon: "/home/tools/adobe-logo.png", bg: "#7fb3c7", text: "#0f2830", blurb: "Photoshop and Illustrator for photo editing and the occasional custom graphic." },
      { name: "Vercel", icon: "/home/tools/vercel.svg", bg: "#a9b98a", text: "#26301a", blurb: "This portfolio (and my mini-game) is deployed and hosted here." },
    ],
  },
  contact: {
    email: "jasminejackson.designs@gmail.com",
    resumeHref: "/resume/jasmine-jackson-resume-2026.pdf",
    linkedin: "https://www.linkedin.com/in/jasminejackson19/",
    github: "https://github.com/jasminejackson19",
    instagram: { handle: "@allthatdesigns", href: "https://www.instagram.com/allthatdesigns/" },
  },
};
